export enum ActionTypePhotoProfileUser {
    PHOTO_PROFILE_USER_START = 'PHOTO_PROFILE_USER_START',
    PHOTO_PROFILE_USER_SUCCESS = 'PHOTO_PROFILE_USER_SUCCESS',
    PHOTO_PROFILE_USER_ERROR = 'PHOTO_PROFILE_USER_ERROR'
}

export enum ActionTypeDeletePhotoProfileUser {
    DELETE_PHOTO_PROFILE_USER_START = 'DELETE_PHOTO_PROFILE_USER_START',
    DELETE_PHOTO_PROFILE_USER_SUCCESS = 'DELETE_PHOTO_PROFILE_USER_SUCCESS',
    DELETE_PHOTO_PROFILE_USER_ERROR = 'DELETE_PHOTO_PROFILE_USER_ERROR'
}